"""SEO 問題代碼與顯示標籤（爬蟲、報告、CI 共用）。"""

from __future__ import annotations

ISSUE_LABELS: dict[str, str] = {
    "missing_title": "缺少 title",
    "title_too_long": "title 超過 60 字元",
    "title_too_short": "title 少於 10 字元",
    "missing_meta_description": "缺少 meta description",
    "meta_description_too_long": "meta description 超過 160 字元",
    "meta_description_too_short": "meta description 少於 50 字元",
    "missing_h1": "缺少 H1",
    "multiple_h1": "多個 H1",
    "broken_image": "圖片連結失效",
    "missing_alt": "圖片缺少 alt",
    "broken_internal_link": "內部連結失效",
    "http_error": "HTTP 錯誤",
    "orphan_page": "孤立頁（無內部連入）",
    "duplicate_title": "重複 title",
    "duplicate_meta_description": "重複 meta description",
    "blocked_by_robots": "robots.txt 封鎖",
    "meta_noindex": "meta noindex",
    "lighthouse_seo_low": "Lighthouse SEO < 90",
    "lighthouse_perf_low": "Lighthouse 效能 < 50",
    "missing_og_tags": "缺少 Open Graph",
    "missing_json_ld": "缺少 JSON-LD",
    "json_ld_missing_type": "JSON-LD 缺少預期 @type",
    "missing_canonical": "缺少 canonical",
    "canonical_mismatch": "canonical 與 URL 不一致",
    "thin_content": "內容過薄（字數不足）",
    "missing_html_lang": "缺少 html lang",
    "missing_viewport": "缺少 viewport meta",
    "redirect_chain": "多段重新導向",
    "title_equals_h1": "title 與 H1 完全相同",
    "hreflang_missing_self": "hreflang 缺少自引用",
    "hreflang_target_error": "hreflang 目標錯誤或不可達",
    "hreflang_no_return": "hreflang 缺少反向連結",
    "insecure_page": "使用 HTTP（非 HTTPS）",
    "mixed_content": "HTTPS 頁含 HTTP 資源",
    "url_too_long": "URL 過長",
    "url_many_parameters": "URL 查詢參數過多",
    "duplicate_content": "內容重複（hash 相同）",
    "duplicate_h2": "重複 H2",
    "missing_h2": "缺少 H2（長文頁）",
    "title_pixels_too_wide": "Title SERP 像素過寬",
    "meta_pixels_too_wide": "Meta SERP 像素過寬",
    "pagination_target_missing": "分頁連結目標未爬取",
    "pagination_target_error": "分頁連結目標錯誤",
    "duplicate_anchor_text": "錨文字重複指向多個 URL",
    "empty_anchor_text": "內鏈錨文字為空",
    "non_descriptive_anchor": "非描述性錨文字（如「點此」）",
    "image_missing_dimensions": "圖片缺少 width/height",
    "image_oversized": "圖片標示尺寸過大",
}
